### ISSUE TITLE
your example page is broken

### ISSUE THREAD

**Issue by fc** [pbauerochse/searchable-option-list#11]
The examples are broken since a rename of the JavaScript occurred:
http://pbauerochse.github.io/searchable-option-list/examples.html

Update the linked JavaScript file to:
https://rawgit.com/pbauerochse/searchable-option-list/master/sol.js

**Comment by pbauerochse** [comment]
Hi fc,

thanks for the hint. I really forgot to update the path after the renaming. I'm still having some css isssues on the example page. I will work on that soon.

Thanks for your patience.

Cheers

Patrick
