### ISSUE TITLE
IE8 does not support input event

### ISSUE THREAD

**Issue by fc** [pbauerochse/searchable-option-list#12]
The input event is not supported in IE8 according to here (it is supported in IE9+):
http://help.dottoro.com/ljhxklln.php

This modification will detect changes on the value property using the propertychange event:
```
            this.$input
                .focus(function () { self.open(); })
                .on('propertychange input', function (e) {
                    var valueChanged = false;
                    if (e.type=='propertychange') {
                        valueChanged = e.originalEvent.propertyName=='value';
                    } else {
                        valueChanged = true;
                    }
                    if (valueChanged) {
                        self._applySearchTermFilter();
                    }
                });

```

**Comment by fc** [comment]
I'm still new to working with git/github and sent the fix to you as a pull request (is that how this is supposed to work haha ??)...

It didn't look like it would break anything and the input events are still manually triggered via trigger('input') when needed.

**Comment by pbauerochse** [comment]
Hi @fc ,

I merged your pull request. Thanks for contributing.

Cheers

Patrick
