### ISSUE TITLE
Invalid item type found undefined Error

### ISSUE THREAD

**Issue by bosesabari** [pbauerochse/searchable-option-list#18]
$(function () {
        $('#my-select').searchableOptionList({
            data: function () {
                var a = document.getElementById("<%= hfjsonstring.ClientID %>").value;
                alert(a);
                return a;
            }
        });
    });

I just take your sample SOL format data as "JSON" format in server side and changed as String format assigned to hidden field and that format assigned into client side  variable "a" that SOL JSON format also coming correctly and also i returned my variable in this script, but its showing the error "Invalid item type found undefined".

**Comment by bosesabari** [comment]
<script type="text/javascript">
    $(function () {
        $('#my-select').searchableOptionList({
            data: function () {
                var a = document.getElementById("<%= hfjsonstring.ClientID %>").value;
                alert(a);
                return a;
            }
        });
    });
</script>

**Comment by pbauerochse** [comment]
Hi @bosesabari ,

I see two problems with your script:

1. you are having server interpreted markup in your JavaScript. `document.getElementById("<%= hfjsonstring.ClientID %>")` will not replace your variable `hfjsonstring.ClientID` unless the whole JavaScript block gets interpreted by your server. But SOL is fully client side script (gets executed in the browser of the user so no server side expressions). For SOL you need to replace `<%= hfjsonstring.ClientID %>` with an actual id as string (e.g. `document.getElementById("myHiddenField").value`)

2. if your `alert(a)` outputs the correct json then you just need to transform it into a JSON object and return that. `document.getElementById("someId").value` returns a *string*  but SOL requires the data function to return a JSON object. So please try something like this: `return jQuery.parseJSON(a);`

Please check if that works.

Cheers

Patrick
