### ISSUE TITLE
Change style for scrollbar and checkbox

### ISSUE THREAD

**Issue by OnPe** [pbauerochse/searchable-option-list#24]
Is there any option, how to change style for scrollbar in large select list and for checkboxes?

**Comment by pbauerochse** [comment]
Hi @OnPe ,

the styling of the scrollbar depends on your browser / operating system. There is no guarantee that you can style it and that it will work on all systems and browser combinations equally but you might want to have a look at http://webdesign.tutsplus.com/articles/quick-tip-styling-scrollbars-to-match-your-ui-design--webdesign-9430 for example.

As for the checkboxes mostly the same rule applies. Another option would be to use custom checkbox like components but then the form submitting mechanism would be a bit trickier so I used regular checkboxes / radios.

Cheers

Patrick
