### ISSUE TITLE
$(...).searchableOptionList is not a function

### ISSUE THREAD

**Issue by sbaldwin24** [pbauerochse/searchable-option-list#25]
Not sure why I keep getting this error. The JS file is correctly placed after jQuery and _searchableOptionList_ is clearly defined. I am using Handlebars and Gulp, not sure if that is causing the issue.

**Comment by sbaldwin24** [comment]
Fixed! There was an instance of ` jQuery.noConflict();` in one of my JS file.

**Comment by sbaldwin24** [comment]
Forgot to mention, I had to add a setTimeout function...
`  $(function() {
    setTimeout(function() {
      $('#my-select').searchableOptionList();
    }, 3000);
  });`

**Comment by pbauerochse** [comment]
Hi @sbaldwin24,

glad to hear that you found the error. Just out of curiosity: do you know the reason why you have to initialize sol after the 3 second delay?

Patrick

**Comment by zombiekaninchen** [comment]
I used 
`jQuery.noConflict();
$('#my-select').searchableOptionList();
`

and it worked... Thanks
