### ISSUE TITLE
How to get selected values in an array 

### ISSUE THREAD

**Issue by shivarambodumalla** [pbauerochse/searchable-option-list#34]
HI i was trying to get the selected values in to an arry will you please help me how to get them ....

**Comment by pbauerochse** [comment]
Hi @shivarambodumalla ,

you could do something like this:

```
var solOptions = { /* options omitted */ };
var sol = $('#mySelect').searchableOptionList();

// later

var selectedOptionsAsArray = sol.getSelection();
```

This will not give you the internal data structure but the actual selected checkboxes/radios instead.

Let me know if that helped you.

Cheers

Patrick

**Comment by ikramcheb** [comment]
Hi,
How can I get the internal values, I don't want  the checkbox container
thank you

**Comment by pbauerochse** [comment]
Hi @ikramcheb,

the internal data structure is attached to the input as ```sol-item``` data attribute so you could do this to convert the inputs to an array of the internal data representation:

```javascript
var asInputs = sol.getSelection(),
    asInternalRepresentation = [];

// iterate over the selected items/dom elements
// extract the 'sol-item' data from it and store it in the other array
for (var i = 0; i < asInputs.length; i++) {
    asInternalRepresentation[i] = asInputs[i].data('sol-item');
}
```

**Comment by ikramcheb** [comment]
Hi, 
I got the following error
TypeError: asInputs[i].data is not a function
noting that sol.getSelections return an array of input, so the problem is how to extract the 'sol-item'

**Comment by pbauerochse** [comment]
I thought I was returning jQuery objects but according to your error message it seems to be plain DOM elements then. The solution then is to wrap the object with jQuery again so 

```javascript
var asInputs = sol.getSelection(),
    asInternalRepresentation = [];

// iterate over the selected items/dom elements
// extract the 'sol-item' data from it and store it in the other array
for (var i = 0; i < asInputs.length; i++) {
    // change this
    // asInternalRepresentation[i] = asInputs[i].data('sol-item');
    // to this
    asInternalRepresentation[i] = $(asInputs[i]).data('sol-item');
}
```

should do the trick. Let me know if this worked.

Cheers

**Comment by ikramcheb** [comment]
yes thanks, 
just add label
$(asInputs[i]).data('sol-item').label
