### ISSUE TITLE
Mixed content stops example page from rendering.

### ISSUE THREAD

**Issue by WrathZA** [pbauerochse/searchable-option-list#35]
![capture](https://cloud.githubusercontent.com/assets/3757315/15145000/55081aa4-16b3-11e6-9354-addbaa2e935e.JPG)

Mixed Content: The page at 'https://pbauerochse.github.io/searchable-option-list/examples.html' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Open+Sans'. This request has been blocked; the content must be served over HTTPS.

Switching the CDN links to HTTPS will resolve.

**Comment by pbauerochse** [comment]
Thanks for the hint @WrathZA . Just fixed it. Should be working now
