### ISSUE TITLE
IE8 doesn't support trim

### ISSUE THREAD

**Issue by fc** [pbauerochse/searchable-option-list#9]
Was doing some cross-browser testing and IE8 apparently doesn't have trim support which is used a few times.

If you choose to include the trim prototype, you could use this:
```javascript
if(typeof String.prototype.trim !== 'function') {
  String.prototype.trim = function() {
    return this.replace(/^\s+|\s+$/g, ''); 
  }
}
```

if you choose to test IE8, you can download a virtual machine image here:
https://www.modern.ie/virtualization-tools

**Comment by pbauerochse** [comment]
Hi @fc,

thanks for the provided fix. I just included it in the most recent sol.js. I wasn't aware that sol even slightly works in IE8 :D

Cheers

Patrick
